### ISSUE TITLE
20231031 중간 이전 전체 검토 결과

### ISSUE THREAD

**Issue by MisooKim2** [mine-park/PY202309#3]
### 없는 파일
- practice/week5/turtle.ipynb
	- 위 파일 이름이나 위치를 다시 확인하세요. 해당 소스 파일 채점이 수행되지 않습니다.

### 워닝 있음. 아래 파일/워닝메세지/솔루션을 확인하세요
- WARNING in challenge/week6/function
    - 10:Unused argument 'task_lis'	def display_tasks(task_lis): # display tasks function
        - 해당 함수에서 task_lis 변수를 사용하고 있지 않습니다. 매개변수를 지우거나 task_lis 를 사용하도록 수정해주세요. 

### 기능/코드 대비 주석이 부족합니다. 주석을 추가하거나 쪼개세요.
- Insufficient comments in challenge/week3/list_and_tuple
- Insufficient comments in project/week8/search_engine

**Comment by mine-park** [comment]
없는 파일 다시 생성했습니다. 해당 파일 이슈 해결했습니다!
워닝 있는 파일은 challenge/week7/todo 및 challenge/week7/todo_extend 파일이었습니다. 해당 파일 이슈 해결했습니다!
주석 부족한 파일 주석 추가했습니다. 해당 파일 이슈 해결했습니다!
